# Generated by Django 5.1.6 on 2025-02-16 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_type', models.IntegerField(choices=[(0, 'Type 0'), (1, 'Type 1'), (2, 'Type 2')])),
                ('model_file', models.FileField(upload_to='models/')),
                ('accuracy', models.FloatField()),
                ('precision', models.FloatField()),
                ('recall', models.FloatField()),
                ('mae', models.FloatField()),
                ('mse', models.FloatField()),
                ('f1_score', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
