# Generated by Django 5.1.6 on 2025-02-16 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IoTGeneratedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('second', models.FloatField()),
                ('src', models.IntegerField()),
                ('dst', models.IntegerField()),
                ('packetcount', models.IntegerField()),
                ('src_ratio', models.FloatField()),
                ('dst_ratio', models.FloatField()),
                ('src_duration_ratio', models.FloatField()),
                ('dst_duration_ratio', models.FloatField()),
                ('TotalPacketDuration', models.FloatField()),
                ('TotalPacketLenght', models.IntegerField()),
                ('src_packet_ratio', models.FloatField()),
                ('dst_packet_ratio', models.FloatField()),
                ('DioCount', models.IntegerField()),
                ('DisCount', models.IntegerField()),
                ('DaoCount', models.IntegerField()),
                ('OtherMsg', models.IntegerField()),
                ('label', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
